services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    networks:
      - alpaca-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    networks:
      - alpaca-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ingestion:
    build: ./ingestion
    networks:
      - alpaca-network
    depends_on:
      - kafka
    environment:
      ALPACA_API_KEY: ${ALPACA_API_KEY}
      ALPACA_API_SECRET: ${ALPACA_API_SECRET}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: unless-stopped

  jobmanager:
    build: ./flink-job
    command: jobmanager
    networks:
      - alpaca-network
    ports:
      - "8081:8081"
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        jobmanager.memory.process.size: 1600m

  taskmanager:
    build: ./flink-job
    command: taskmanager
    networks:
      - alpaca-network
    depends_on:
      - jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        taskmanager.memory.process.size: 1600m

  pyflink-job:
    build: ./flink-job
    networks:
      - alpaca-network
    depends_on:
      - kafka-init
      - jobmanager
      - taskmanager
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure

  kafka-init:
    image: confluentinc/cp-kafka:7.7.0
    networks:
      - alpaca-network
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Warte auf Kafka...'
      sleep 15
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic raw --partitions 1 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic processed --partitions 1 --replication-factor 1
      echo 'Topics erstellt!'
      "
    restart: "no"

networks:
  alpaca-network:
    driver: bridge